### ISSUE TITLE
Advisory board logos should be black and white and get color when hover upon.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#103]
**Acceptance Criteria:**
- [x] Advisory board logos should be black and white and get color when hover upon.

- [ ] Add the hand instead mouse when you are inside icons. For more details refer the image below.

@partini Please see this detail.

<img width="956" alt="screen shot 2017-01-17 at 1 26 46 pm" src="https://cloud.githubusercontent.com/assets/21961919/22020634/8a32b384-dcb9-11e6-94a8-5e9403091791.png">

**Comment by artaabdullahu** [comment]
@georgeslabreche @dafinaolluri Should the mouse be displays when hovering the logos, like shown picture attach ?
I created earlier check buttons and I saw this task is closed before, I don't know why. Probably is not necessary displaying this kind of mouse.

https://cloud.githubusercontent.com/assets/21961919/22020634/8a32b384-dcb9-11e6-94a8-5e9403091791.png
