### ISSUE TITLE
Chose data source: IDEMS(inside dropdown list).  Which means It is not clickable.

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#106]

**Comment by artaabdullahu** [comment]
Enable IDAMS data with all the functionalities (data is imported and ready to be served because it's imported with the same structure as mgr data, we are not enabling it until we finish all the functionality by using MGR).

**Comment by artaabdullahu** [comment]
I dont have this data of IDAMS.

**Comment by partini** [comment]
@artaabdullahu you can test IDAMS in the online version. There is no dataset like the MGR excel sheets.
