### ISSUE TITLE
Change dropdown of locations to a Search box.

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#112]

**Comment by artaabdullahu** [comment]
- [ ] I think to put scroll in part when you are searching
Have problem with page in general when I use search button. ![search_button](https://cloud.githubusercontent.com/assets/21961919/21497195/ae59ef62-cc23-11e6-9457-442ec138bd39.png)

**Comment by partini** [comment]
@artaabdullahu Explain more specifically what is the problem?

**Comment by artaabdullahu** [comment]
@partini look screenshot above. Po del nje pjese e bardhe poshte krejt po zgjatet faqja.
