### ISSUE TITLE
Tablet design. 

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#117]
Human and Economic Impact. -> I can not see part of "Daths" is hidden. 
![tablet](https://cloud.githubusercontent.com/assets/21961919/21522801/eee22f64-cd08-11e6-9df2-539118b575ab.png)

**Comment by artaabdullahu** [comment]
In Safari it looks there is a problem. See the screenshot below:

<img width="1278" alt="screen shot 2017-01-20 at 11 14 45 pm" src="https://cloud.githubusercontent.com/assets/21961919/22167401/5fa07570-df66-11e6-8f8d-5d336d6d1d8b.png">

**Comment by partini** [comment]
@artaabdullahu send a tablet screenshot since the task is to do tablet design fixes. If it's having issues in safari, create another task in bugs.

**Comment by artaabdullahu** [comment]
@partini Yesaaa 

![image](https://cloud.githubusercontent.com/assets/21961919/22198047/09d5e918-e155-11e6-9331-931972585c9c.png)

**Comment by artaabdullahu** [comment]
@partini In Ipad: part for show data, so to be more specific checkbox is not working well when I click on it. As i told you in practice. 

- [ ] When I click on checkbox is not displayed tick symbol.

**Comment by artaabdullahu** [comment]
@partini Look the picture bellow. I think is more better will be If you can separate those legends. 
![image](https://cloud.githubusercontent.com/assets/21961919/22206278/e318db3e-e17a-11e6-8f3d-17daaeeb8656.png)
