### ISSUE TITLE
As a user I want to see logos in Advisory Board, so I can link them to their website.

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#122]
**Description**
Every logo in the Advisory Board Section 9n the About Page should be linked to website.

**Acceptance Criteria**

- [x] The Advisory Board Section: 1) Logos are not linked to websites. 

- [x] Logos: are not connected to websites of organizations.  "I believe I had sent them before to you. Let me know if you need them again" (**Behar Xharra)**

- [x] c)Footer:
i.	Size - Make it a bit smaller ( size of fonts, logo, etc)
ii.	Add Twitter, Gmail (or email), CGS logo, and LinkedIn in the social media buttons. 
1.	Connect Email logo to “info.cgs.bd@gmail.com”’ 
2.	connect LInkedIn and Twitter Logo to Facebook for now; 
3.	Connect CGS Logo to http://cgsdu.org/

**Comment by partini** [comment]
@dafinaolluri we need info on these?

**Comment by dafinaolluri** [comment]
@partini Links are provided for the Advisory Board

- [x] Metropolitan Chamber of Commerce and Industry -  http://www.mccibd.org/
- [x] The Daily Star - http://www.thedailystar.net/
- [x] SEHD Bangladesh -  http://www.sehd.org/
- [x] Action Aid Bangladesh  - http://www.actionaid.org/bangladesh
- [x] University of Dhaka - http://www.univdhaka.edu/
- [x] Center for Genocide Studies - http://cgsdu.org/
- [x] Microgrovernance Research Initiative - https://www.facebook.com/microgovernance/
- [x] Bangladesh Police - http://www.police.gov.bd/
- [x] National Defence College - http://www.ndc.gov.bd/
- [x] Stop Violence Coalition - http://stopviolencebd.org/

**Comment by artaabdullahu** [comment]
@partini @dafinaolluri  Gmail is not connected with to G+ icon in the footer
