### ISSUE TITLE
As an Admin I want to be able to add another section in About Page where I can describe existing data sources MGR and IDAMS?

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#123]
**Description**
Adding another section in About Page where I can include the existing data sources **MGR** and **IDAMS**?

**Comment by partini** [comment]
@dafinaolluri We need more info about this. What do we put in that section, please get all the informations.

**Comment by simonfossom** [comment]
I can work on this if you need me to.

**Comment by partini** [comment]
@OzrenMuic @dafinaolluri We added a Popup modal form on the visualizer instead. I am closing this issue.
