### ISSUE TITLE
As a user I want to be able when scrolling down in the BPO platform I can see Timeline and Footer.

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#127]
**Description**

In the Size: the existing frames (Map, Story Line) are not visualised in the same way they were designed in the mockups. The are thick, wide, and short. They should be longer, to cover one full screen. So, upon scrolling down, the user should see the Timeline and Footer. 

**Acceptance Criteria**

- [ ]  The website frame is stretched too wide. It should be a bit thinner, leaner, as is in the mockups.

**Comment by partini** [comment]
The elements are designed as per the mockup design. 
Need more details/specifics on what do we make thinner, what leaner?
