### ISSUE TITLE
Please rename the Search Bar to: “Search insights for specific division, districts, or upazilas” 

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#131]
**Description**

The Search Bar should be renamed to “Search insights for specific division, districts, or upazilas” 

**Acceptance Criteria**

- [x] Make the font size smaller.

- [x]  If it is too long, then do it “Search insights for divisions, districts, upazilas”

- [x]  Add : font-size: 14px;
                  font-family: Lato;
                  line-height: 17px;

**Comment by partini** [comment]
See image:
![screen shot 2017-01-18 at 3 43 24 pm](https://cloud.githubusercontent.com/assets/7932995/22068378/1fecf71e-dd95-11e6-8b11-b70daee2fd8d.png)

**Comment by artaabdullahu** [comment]
@partini OK!
