### ISSUE TITLE
As a user when I click in the Search Bar I want to be able to see the drop-down list in a consistent manner.

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#132]
**Description**
The Search Bar does not work properly.  The drop-down list as it stands is quite overwhelming. Bullets look weird. It is not easy to navigate.

**Acceptance Criteria**
- [x] When I click in one name, it doesn’t hover on, and there is no way to tell whether I clicked on it or not. 
- [x] 	When it shows results, the drop-down list does not disappear. 
- [x] 	When I search it feels like it is freezing, and takes time to load result. Yielding results is not flowable.
- [x] 	I would suggest you limit results suggestions - ex. When typing Dhaka show only three suggestions:  “Dhaka Division” or “Dhaka District” or “Dhaka Savar” no more. When you start adding all the upazilas, etc….it becomes crazy.

**Comment by artaabdullahu** [comment]
I want to explain with example a problem about after cilcked search button. Example: When I am  in Dhaka, Tanguail. It show me a map for this country. -> until in this point is OK.
After When I am searching for another country and when I clicked enter or I clicked with mouse is not working(it means -> is not showing me map for this country that I searched). (alb: Nese jon ne Dhaka, Tanguail. Me shfaqet mire map per ket vend. Me pastaj kur kerkoj per nje vend tjeter dhe une shtypa enter ose klikovame maus nuk punon [qe do te thote se nuk me shfaqet mapi per vendin e keruar])
