### ISSUE TITLE
The line of the Map Frame and the line of the Text Frame are not the same. One is thinner, the other is thicker. 

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#138]
**Description**
Please see the picture below:

- [x] The Numbers : <10; 11 to 50 .... etc - should to have **font-family: Lato;**

![image](https://cloud.githubusercontent.com/assets/24916965/22000924/4af07af2-dc42-11e6-8bed-823c1a1d1de9.png)

**Comment by partini** [comment]
@artaabdullahu the text style inside the box is not changeable.

**Comment by artaabdullahu** [comment]
Ok @partini ! @georgeslabreche Is it okay?
