### ISSUE TITLE
The Download data features are missing. 

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#152]
We need to set a time to discuss this.

**Comment by partini** [comment]
@dafinaolluri @artaabdullahu I did a simpler version of this so we at least can download the data directly.

**Comment by artaabdullahu** [comment]
Should to be font-family as picture bellow.
<img width="453" alt="screen shot 2017-01-26 at 2 29 39 pm" src="https://cloud.githubusercontent.com/assets/21961919/22333045/3f0ca226-e3d4-11e6-9ae5-b980aadd36a8.png">
