### ISSUE TITLE
dimensions of first section on about page

### ISSUE THREAD

**Issue by simonfossom** [opendatakosovo/bpo#161]
There should be 200px from the title to the top and from the subtitle to the next section

**Comment by artaabdullahu** [comment]
@OzrenMuic Is that 200 px from Advancing understanding of peace and tolerance through data insights to the next section that starts white color (the line who separate two different section with two different background) or Hosted by the Centre for Genocide Studies, University of Dhaka to the next section that starts white color...?
<img width="1280" alt="screen shot 2017-03-06 at 3 33 44 pm" src="https://cloud.githubusercontent.com/assets/21961919/23614195/7200c3ac-0282-11e7-8b95-cbd50abeea9f.png">
