### ISSUE TITLE
Small header on About screen

### ISSUE THREAD

**Issue by simonfossom** [opendatakosovo/bpo#167]
When scrolling past first section of About page, title should shrink and move to the left corner (with left margin same as the right margin of the 'Enter' button 

Like this:
![header small](https://cloud.githubusercontent.com/assets/8134850/22288246/57a83356-e2f6-11e6-99d4-c7043547f4a9.jpg)

**Comment by artaabdullahu** [comment]
Only in two different devices the navbar is not full. 
<img width="507" alt="screen shot 2017-03-08 at 10 30 39 pm" src="https://cloud.githubusercontent.com/assets/21961919/23724923/ee492ecc-044e-11e7-920f-cffe5ced4df9.png">
<img width="486" alt="screen shot 2017-03-08 at 10 30 57 pm" src="https://cloud.githubusercontent.com/assets/21961919/23724924/ee6a014c-044e-11e7-8588-d4b5715a9c51.png">

**Comment by artaabdullahu** [comment]
The title **Bangladesh Peace Observatory** should be: 
(Also, Ozren has placed a screenshot as how should look the part of title )
<img width="1134" alt="screen shot 2017-03-09 at 11 59 34 pm" src="https://cloud.githubusercontent.com/assets/21961919/23774664/165508ba-0525-11e7-8136-acb4622870d0.png">

**Comment by artaabdullahu** [comment]
@diamanthaxhimusa  you forgot to put font-family ......etc. So, I can not to accept.
