### ISSUE TITLE
As a user on a Division profile page, I want to see how its Upazilas compare and rank with each other.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#17]

**Comment by simonfossom** [comment]
This could be a bit problematic in terms of number of data point to present.
Some divisions have up to hundred-ish upazilas. 

<img width="1073" alt="screen shot 2016-10-02 at 17 38 24" src="https://cloud.githubusercontent.com/assets/8134850/19021692/3f327810-88c7-11e6-9bae-a9db36580ddb.png">

do you think going with top 10 or 20 would be enough?

I mean, we can make that graph but it will be hard to read data.
