### ISSUE TITLE
Parameters for Downloading Data

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#185]
**Description**

Excel DATA: Incident Date; type, description (if available);  Actor 1 (perpetrator) and Actor 2 (Victim); Upazila, District, Division, Lat and Long, # of deaths, # of Injuries; # of property damage; source: (link) or name of (Newspaper);
PDF: Map, Story, and Timeline + Excel Data below.

Note 2 - Actors should be perpetrator and victim under IDAMS and not Instigator and Target; if there are more than two actors as perpetrators, please combine them into one tab, separated with comma. Same applies to victims.

**Comment by partini** [comment]
Naming should follow this structure:
Cittagong division ranked 1st in the country in Destruction of Property
Dhaka District ranked ....
Dhaka District ranked 1st in Dhaka Division with 600 injuries.
We should have three types of downloading:
Download PDF, Download raw data, Download aggregated data
