### ISSUE TITLE
As a user, I want to be presented general stats on the landing page which are aggregates of mostly static thurs party pages we can pull data from. This is so that we can have a statistical overview of the country from sourced from authoritative data sources.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#2]

**Comment by bxharra** [comment]
Beauty!

For now - the following seem to be the most probable sources we can use: 
-- **MGR data** (confirmed and dataset + codebook sent to Georges)
-- **IDAMS Data** (validation of 1300 incidents to take place in next two weeks; need to discuss with Georges the potential combination of a subset of data i.e. Arson + IED + political dispute).
-- **Bangladesh Population Census** (TBD discussed with Georges about inclusion of specific demographic data)
-- **ACLED data** (they apparently have an API - http://www.acleddata.com/wp-content/uploads/2016/07/ACLED_API-User-Guide_28072016.pdf)
-- **University of Maryland - START** - (open data; not sure about API).

-- **Police data** - confirmed in principle but could take some time (I would put this as a second priority)

Whereas - 

-- South Asia Terrorism data - we will not include this source of data in the first iteration.
