### ISSUE TITLE
Home button should stay on the right side.

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#207]
**Description**
Home button should always be on the right side.
<img width="828" alt="screen shot 2017-03-02 at 1 41 08 pm" src="https://cloud.githubusercontent.com/assets/21961919/23507585/0c134fc4-ff4e-11e6-9b6d-3fecef6fdaf4.png">

**Comment by artaabdullahu** [comment]
After they said to added **Data Disclaimer** in small size **Home** and **Data Disclaimer** should be in new line and they should be Home and after that should be **Data Disclaimer**
<img width="281" alt="screen shot 2017-03-07 at 4 44 36 pm" src="https://cloud.githubusercontent.com/assets/21961919/23664400/bc4da668-0355-11e7-8b84-a7cea44a984e.png">

<img width="1136" alt="screen shot 2017-03-07 at 4 49 06 pm" src="https://cloud.githubusercontent.com/assets/21961919/23664506/0d564d08-0356-11e7-9f08-e5cbfb55682d.png">

**Comment by artaabdullahu** [comment]
Maybe the reason why is looking like this is you have changed some code in footer part.
<img width="612" alt="screen shot 2017-03-08 at 10 01 32 am" src="https://cloud.githubusercontent.com/assets/21961919/23696981/3bd11d62-03e6-11e7-8eb1-d7ffb16f16d0.png">

**Comment by diamanthaxhimusa** [comment]
@artaabdullahu can you please re-test this?
