### ISSUE TITLE
On the right side of the footer we have a white space in the vertical direction.[Division page]

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#209]
**Description**
With red line I tried to show where is this problem.
<img width="1280" alt="screen shot 2017-03-02 at 1 51 43 pm" src="https://cloud.githubusercontent.com/assets/21961919/23509075/d98f2666-ff54-11e6-946c-50f5d2211d67.png">

**Comment by diamanthaxhimusa** [comment]
@artaabdullahu can you please attach the screenshot, i can't see it!

**Comment by artaabdullahu** [comment]
On this size whole footer should be center.
<img width="968" alt="screen shot 2017-03-07 at 4 57 03 pm" src="https://cloud.githubusercontent.com/assets/21961919/23664879/21f00dfc-0357-11e7-8de4-07a81927c8ca.png">

**Comment by artaabdullahu** [comment]
On this page footer is look like this:
<img width="598" alt="screen shot 2017-03-08 at 9 55 33 am" src="https://cloud.githubusercontent.com/assets/21961919/23696797/7c7447a0-03e5-11e7-9c40-127160b1145c.png">
