### ISSUE TITLE
When downloading reported violence in Bangladesh, there should be a (X) sign or continue to go to the main page.

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#213]

**Comment by artaabdullahu** [comment]
For small size of devices this pop up for download is too big. So, I cann ot to see (X) to close this form.
<img width="1059" alt="screen shot 2017-03-06 at 2 49 44 pm" src="https://cloud.githubusercontent.com/assets/21961919/23612605/53a104ea-027c-11e7-9a90-3d4001470943.png">
