### ISSUE TITLE
Pop up for Print Media Review and Online Media Review it's too large for the size on small devices.

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#216]
**Description**
This pop up is too large for the size, so in small devices I can not to cancel that. Well, this pop up should be responsive.
<img width="419" alt="screen shot 2017-03-02 at 4 21 10 pm" src="https://cloud.githubusercontent.com/assets/21961919/23513420/48da56b2-ff64-11e6-8824-1727d6206282.png">

**Comment by partini** [comment]
Archiving this one, there is no popup now.
