### ISSUE TITLE
The dropdown list of "National Rank of X Division" should to fix part of column. 

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#219]
<img width="1266" alt="screen shot 2017-03-03 at 1 56 53 pm" src="https://cloud.githubusercontent.com/assets/21961919/23552049/2c8b43f2-001a-11e7-8db7-6b28313a4511.png">

**Comment by dafinaolluri** [comment]
@artaabdullahu @partini I am closing this one because its a duplication of another task we finished.

**Comment by artaabdullahu** [comment]
@dafinaolluri With which task is the same? I created this because still stands as a bug.
<img width="1270" alt="screen shot 2017-03-07 at 8 31 09 pm" src="https://cloud.githubusercontent.com/assets/21961919/23674102/0543e390-0375-11e7-8e37-a64b89952672.png">
