### ISSUE TITLE
Rename Violence Type

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/bpo#234]
**Violence Type**

- [ ] Violent Extremism (Islamist) > Violent Extremism (Non-Secular) 

- [ ] Violent  Extremism (Rebel)    > Violent Extremism (Secular)

National Overview of Division

- [ ] 'Islamic State of Iraq and Syria' to 'Neo-JMB'?

**Comment by partini** [comment]
@dafinaolluri Can we make sure it's Neo-JMB instead of New-JMB?
As far as I know it's New-JMB.

**Comment by dafinaolluri** [comment]
@partini I sent an email to Hossain, hopefully he'll be back tonight to know for sure the answer.
