### ISSUE TITLE
#31 As a User - I would like to see a relationship diagram (Sankey Diagrams) between perpetrators and victims

### ISSUE THREAD

**Issue by bxharra** [opendatakosovo/bpo#31]

**Comment by simonfossom** [comment]
Sankey is not really good for relationship diagram. It displays proportionally to the flow quantity. 
It's good for showing how money or energy is spent. 

Also, as I have understood, this site is for wide audience so I wouldn't go into charts unless they are really really simple.

Best would be to just show statements with simple data backing them up.

**Comment by bxharra** [comment]
I imagine Sankey offering a good way to show the biggest perpetrators and victims in relation to each other! Though agree it does not show numbers, rather the proportion (which is great but that may complicate matters in terms of simplicity). I will wait to see the first iteration then, and we can discuss.
