### ISSUE TITLE
The "not enough data" text doesn't fit in the div. Remove it and replace it by a modal that appears when trying to expand the div.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#73]
<img width="640" alt="screen shot 2016-12-17 at 10 27 46 pm" src="https://cloud.githubusercontent.com/assets/1258236/21289863/305d460e-c4a8-11e6-9f66-e3f91155408d.png">
<img width="645" alt="screen shot 2016-12-17 at 10 27 38 pm" src="https://cloud.githubusercontent.com/assets/1258236/21289864/305fd996-c4a8-11e6-96f0-004df1290cbd.png">

**Comment by georgeslabreche** [comment]
@partini no modals with message that prevents expanding the div. It just opens and shows an empty chart.

**Comment by artaabdullahu** [comment]
Hi @georgeslabreche , i think that the version which shows the "Not enough data" inside the chart is better than the modal? If you agree I wold close this issue.

**Comment by artaabdullahu** [comment]
We dont have any answers. Let us understand this that we will do same with design.
