### ISSUE TITLE
There is a trend arrow even when there is not enough data. This should NOT be possible.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#78]
<img width="599" alt="screen shot 2016-12-17 at 11 56 48 pm" src="https://cloud.githubusercontent.com/assets/1258236/21290282/92934a06-c4b4-11e6-945f-862e7047eed8.png">

**Comment by georgeslabreche** [comment]
@partini This is still an issue, see screenshot:

<img width="551" alt="screen shot 2016-12-19 at 10 54 05 am" src="https://cloud.githubusercontent.com/assets/1258236/21308303/ac7b7bca-c5d9-11e6-8bab-301a80ff05fd.png">

**Comment by artaabdullahu** [comment]
Hey Georges, i think that the version which shows the "Not enough data" inside the chart is better than the modal? If you agree I wold close this issue.

**Comment by artaabdullahu** [comment]
![increase_injury](https://cloud.githubusercontent.com/assets/21961919/21499334/290cbdf0-cc35-11e6-8877-556e77b6b084.png)
Why is symbol that have increase injury count but In fact inside not have data to shows??

**Comment by artaabdullahu** [comment]
Functionality is OK, but should to be responsive this part.
![image](https://cloud.githubusercontent.com/assets/21961919/22423366/94b566a2-e6f1-11e6-956c-c75d62b87cd0.png)
