### ISSUE TITLE
Division ranking.

### ISSUE THREAD

**Issue by partini** [opendatakosovo/bpo#83]

**Comment by artaabdullahu** [comment]
Form is not working good in time. Also the design is a little bit different. 
![division_ranking](https://cloud.githubusercontent.com/assets/21961919/21496483/2daa6d0a-cc1f-11e6-9f40-be6e2ecb2a88.png)

**Comment by artaabdullahu** [comment]
Also should to add "col" for small and xs devices.
![deivisionranked_phone](https://cloud.githubusercontent.com/assets/21961919/21496746/f992e3ba-cc20-11e6-842a-2f00bad10531.png)

**Comment by partini** [comment]
@artaabdullahu What do you mean not working good? Please explain.

**Comment by artaabdullahu** [comment]
I added col-xs-3 for mini devices to save the original shape. I mean three column to be inline. See screenshot!
![division_ranking](https://cloud.githubusercontent.com/assets/21961919/21519752/e1231ec4-ccef-11e6-913f-aae93d8e5f6b.png)
