### ISSUE TITLE
Have some errors here

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#88]

**Comment by artaabdullahu** [comment]
![some_errors](https://cloud.githubusercontent.com/assets/21961919/21314579/1d02edf6-c5f8-11e6-937c-1ad5358c4510.png)

**Comment by artaabdullahu** [comment]
I tested this section before published new version. Now are not these error.

**Comment by georgeslabreche** [comment]
@artaabdullahu please use more descriptive title!
