### ISSUE TITLE
Add Show data.

### ISSUE THREAD

**Issue by artaabdullahu** [opendatakosovo/bpo#89]
![show](https://cloud.githubusercontent.com/assets/21961919/21317055/ccaf1666-c603-11e6-9cd0-03672ad1d6a5.png)

**Comment by artaabdullahu** [comment]
Let it be as we have in design from. Example: Incidents with a specific shaping and yellow color.....

**Comment by partini** [comment]
@artaabdullahu this is the default behavior of highcharts and we don't have the time to intervene in this.
