### ISSUE TITLE
Positions of the elements are all over the place

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#92]
- [x] Bangladesh Peace Observatory should be in the center of upper half of the screen round 25% of hight
- [x] Enter the Observatory should be right in center
- [ ] all the text under the the button should be nailed 70px from the bottom of the screen with double spacing between rows.
- [x] Bangladesh Peace Observatory should be bold.

**Comment by partini** [comment]
@georgeslabreche @dafinaolluri  Closing this issue because we agreed to change the design of the header.
