### ISSUE TITLE
color in design #FDA200 and this is color on website #FFAA12

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#93]
Colors are not chosen randomly and approximation is not good enough.

**Comment by artaabdullahu** [comment]
To find more easy -> ![enter](https://cloud.githubusercontent.com/assets/21961919/21389615/ed2cc8e0-c782-11e6-8f8d-0adc0306f352.png)

**Comment by partini** [comment]
@artaabdullahu Provide specification.

**Comment by artaabdullahu** [comment]
THis button should to have color #FFAA12! now have #FDA200.
