### ISSUE TITLE
What happened to background gradient?

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/bpo#98]
Here are the CSS attributes for background in design: background-image: linear-gradient(0deg, #003D52 0%, #007CA4 58%); please adapt it to background color

**Comment by partini** [comment]
@artaabdullahu please provide specifications?

**Comment by artaabdullahu** [comment]
@partini  I dont need te write here why I put in NOT ACCEPTED this task because gradient was not completed.

**Comment by artaabdullahu** [comment]
BUt now its ok !
